name: Generate and deploy feeds
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
		steps:
    - uses: actions/checkout@v1

		- name: Instala Python 3
			uses: actions/setup-python@v2
			with:
				python-version: 3.9

		- name: Instala newslinkrss
			run: pip3 install newslinkrss

		- name: Cria diretório que receberá os feeds
			run: mkdir feeds

		- name: Executa newslinkrss
			run: bash generate_feeds.sh

		- name: Deploy
			uses: peaceiris/actions-gh-pages@v2
			env:
				ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
				PUBLISH_BRANCH: gh-pages
				PUBLISH_DIR: ./feeds
