name: Generate and deploy feeds
on:
  schedule: # Run workflow automatically
    - cron: '0 */6 * * *' # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Instala Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Configura locale pt_BR.UTF-8
      run: |
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8

    - name: Instala newslinkrss
      run: pip3 install newslinkrss

    - name: Instala yq
      run: pip3 install yq

    - name: Cria diretório que receberá os feeds
      run: mkdir feeds

    - name: Executa newslinkrss
      run: bash -x generate_feeds.sh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./feeds
